# Generated by Django 5.2.1 on 2025-05-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coredetail',
            name='created_at',
        ),
        migrations.AddField(
            model_name='coredetail',
            name='product_rank',
            field=models.IntegerField(default=1),
        ),
    ]
