# Generated by Django 5.2.1 on 2025-05-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_coredetail_created_at_coredetail_product_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coredetail',
            name='user',
        ),
    ]
