# Generated by Django 5.2.1 on 2025-05-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_coredetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredetail',
            name='product_color',
            field=models.CharField(default='bg-blue-600', max_length=100),
        ),
    ]
